### PR TITLE
New combinatorial benchmarks

### PR DESCRIPTION
**Pull request by elffersj**
Adds the following new benchmarks:
- Dense Linear Ordering Principle
- Relativized Pigeonhole Principle
- s-t connectivity formula
- Thapen's size-width tradeoff formula
- XORification with replacement

I didn't completely understand how to add them to the commandline. Maybe you could do it or explain how it should be done?

### CODE REVIEW

**Comment by elffersj** [comment]
I added command line interfaces for everything except XORification with recycling. For that one, a matrix is needed as input, and I don't know how we would read that with argparse. One idea is to use the SimpleGraphHelper and use the graph as the matrix.

Another issue: in the s-t connectivity formula, we need to specify source and destination vertices on the command line. In general nodes can have arbitrary types, for example in the grid graph we use tuples: (x, y). So currently you need to specify node IDs (0-based).

**Comment by marcvinyals** [comment]
I would suggest to break this pull request into smaller PRs, maybe one per family, so that we can merge the easier parts first. For instance, RPHP looks uncontroversial to me so it can be merged quickly, but as you said s-t connectivity will take some more time.

**Comment by elffersj** [comment]
I now added separate pull requests for RPHP, Dense Ordering Principle and Thapen. s-t connectivity and XORification are probably not ready yet.

**Comment by MassimoLauria** [comment]
Can I close this pull request, and only take care of the new ones?

**Comment by elffersj** [comment]
Yes, thanks.

**Pull request closed without merging**
